# Session settings. 
session:
    # Session passphrase. Change this!
    secret: "sssh secret"
# User logins.
users:
    admin:
        password: "8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918"
        email: admin@example.com
        group: admin

# Have you read the configuration?
die: 0
